FROM ubuntu:latest

RUN apt update && apt install -y python3 python3-pip python3-venv nginx && rm -rf /var/lib/apt/lists/*

COPY backend /app/backend
COPY frontend /app/frontend

WORKDIR /app/backend
RUN python3 -m venv .venv && .venv/bin/pip install fastapi uvicorn python-frontmatter

RUN rm /etc/nginx/sites-enabled/default
COPY nginx.conf /etc/nginx/sites-available/default
RUN ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

EXPOSE 80

COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

CMD ["/app/start.sh"]